// Lessons array with different lesson objects
let lessons = [
  {
    id: 1001,
    subject: "Calculus",
    location: "Leeds",
    description: "",
    price: "£350",
    spaces: 5,
    image: "images/calculus.jpg",
    rating: 4,
  },
  {
    id: 1002,
    subject: "Physical Education",
    location: "Bournemouth",
    description: "",
    price: "£150",
    spaces: 5,
    image: "images/physicalEducation.jpg",
    rating: 4,
  },
  {
    id: 1003,
    subject: "Programming Essentials",
    location: "Liverpool",
    description: "",
    price: "£650",
    spaces: 5,
    image: "images/programming.jpg",
    rating: 3,
  },
  {
    id: 1004,
    subject: "Dance classes",
    location: "Norwich",
    description: "",
    price: "£550",
    spaces: 5,
    image: "images/dance.jpg",
    rating: 3,
  },
  {
    id: 1005,
    subject: "Cyber Security",
    location: "Darlington",
    description: "",
    price: "£375",
    spaces: 5,
    image: "images/cyberSecurity.jpg",
    rating: 4,
  },
  {
    id: 1006,
    subject: "Music Classes",
    location: "Aberdeen",
    description: "",
    price: "£399",
    spaces: 5,
    image: "images/music.jpg",
    rating: 2,
  },
  {
    id: 1007,
    subject: "Woodwork",
    location: "Watford",
    description: "",
    price: "£200",
    spaces: 5,
    image: "images/woodwork.jpg",
    rating: 5,
  },
  {
    id: 1008,
    subject: "Gymnastics",
    location: "Wolverhampton",
    description: "",
    price: "£400",
    spaces: 5,
    image: "images/gymnastics.jpg",
    rating: 4,
  },
  {
    id: 1009,
    subject: "Graphics and Animation",
    location: "Coventry",
    description: "",
    price: "£780",
    spaces: 5,
    image: "images/graphics.jpg",
    rating: 3,
  },
  {
    id: 1010,
    subject: "Photography 101",
    location: "Stockport",
    description: "",
    price: "£395",
    spaces: 5,
    image: "images/photography.jpg",
    rating: 4,
  },
];
